In [6]:
a_list = [1, '4', 9, 'a', 0, 4]

squared_ints = [ e**2 for e in a_list if type(e) == int ]

print(squared_ints)

[1, 81, 0, 16]


In [21]:
word = input('Enter a word:')

chrcnt = dict()
for i in word:
    chrcnt[i] = chrcnt.get(i,0)+1

for i in sorted(chrcnt):
    print(i, chrcnt[i])

Enter a word:ashlesh shetty
  1
a 1
e 2
h 3
l 1
s 3
t 2
y 1


In [27]:
for k,v in chrcnt.items():
    print(k)

a
s
h
l
e
 
t
y


In [36]:
[(index,obj) for index, obj in enumerate(['a','b','z','c'])]
def is_sorted(srt_ls):
    Flag = True
    for index, obj in enumerate(srt_ls):
        if index != len(srt_ls)-1:
            if obj > srt_ls[index+1]:
                Flag = False
    return Flag
is_sorted(['a','b','c'])

True

In [48]:
def shortestpath(n):
    count_mul_3 = 0
    count_add_5 = 0
    while n >=1 :
        if n % 3 ==0:
            n = n//3
            count_mul_3 += 1 
        else: 
            n = n -5
            count_add_5 += 1
    return(count_add_5-1 , count_mul_3)

shortestpath(13)

(2, 1)

In [68]:
text = 'ashleshshetty'
text[::1]

'ashleshshetty'

In [70]:
'yel' in 'yellow' 

True

In [71]:
'yel' not in 'yellow'

False

In [72]:
'y' > 'ashlesh'

True

In [ ]:
import json
climatedict = dict()
with open('minneapolis.json','r') as f:
    climatedict = json.load(f)

In [73]:
state_dict = dict()  
import csv  
with open('us_states.csv','r') as f:
    for i in csv.reader(f):
        state_dict[i[1]] = i[0]

In [ ]:
with open('states.txt', 'r') as f:
    return f.readlines()

In [76]:
class WageCalculator:
    def __init__ (self, wage = 0.0, hours = 0.0):
        self.wage = wage
        self.hours = hours
    
    def cal_gross_pay(self):
        return self.wage * self.hours
        
a_calculator = WageCalculator()
a_calculator.hours = 35
a_calculator.wage = 12.50


print("Total wage is {}.".format(a_calculator.cal_gross_pay()))


Total wage is 437.5.


In [84]:
import numpy as np
x = np.array([1.48,1.41,0.0,0.1])
print(x.argsort())
print(x[x.argsort()])
print(x[x.argsort()][::-1])

[2 3 1 0]
[ 0.    0.1   1.41  1.48]
[ 1.48  1.41  0.1   0.  ]


In [88]:
np.sort(x)
print(x)

[ 1.48  1.41  0.    0.1 ]


In [90]:
x.sort()
print(x)

[ 0.    0.1   1.41  1.48]


In [94]:
# use case of arg sort

sales = np.array([13,21,1,4])
stores = np.array(['alabama','new york', 'minnesota','LA'])

print(sales[sales.argsort()])
print(stores[sales.argsort()])

[ 1  4 13 21]
['minnesota' 'LA' 'alabama' 'new york']


In [ ]:
# Example of numpy load text and argsort
def compare_names_for_years(year1, year2,n):
    import numpy as np
    y1 =  np.loadtxt('yob'+str(year1)+'.txt', delimiter = ',', dtype = str)
    y2 =  np.loadtxt('yob'+str(year2)+'.txt', delimiter = ',', dtype = str)
    
    y1_n = y1[np.argsort(np.array(y1[:,2],dtype =int))[::-1]][:n,0]
    y2_n = y2[np.argsort(np.array(y2[:,2],dtype =int))[::-1]][:n,0]
    return np.intersect1d(y1_n,y2_n)

# compare_names_for_years(2007,2016,20)

## Pandas Apply

In [110]:
import pandas as pd
df = pd.DataFrame({'Col1': [1,2,2,4]})
df['Col2'] = df['Col1'].apply(lambda x: x*5)
df

Col1  Col2
0     1     5
1     2    10
2     2    10
3     4    20

In [111]:
df.sort_values(by = 'Col2', ascending = False)

Col1  Col2
3     4    20
1     2    10
2     2    10
0     1     5

In [113]:
df.duplicated(subset = 'Col2', keep = 'first')

0    False
1    False
2     True
3    False
dtype: bool

In [115]:
df.drop_duplicates(subset = ['Col2'], keep = 'first')

Col1  Col2
0     1     5
1     2    10
3     4    20

In [124]:
df[~(df['Col2'] == 10)]

Col1  Col2
0     1     5
3     4    20